// Generated by https://quicktype.io

export interface DistanceService {
    features: Feature[];
    type:     string;
}

export interface Feature {
    properties: Properties;
    geometry:   Geometry;
    type:       string;
}

export interface Geometry {
    coordinates: Array<Array<number[]>>;
    type:        string;
}

export interface Properties {
    "fill-opacity": number;
    fillColor:      string;
    opacity:        number;
    fill:           string;
    fillOpacity:    number;
    color:          string;
    contour:        number;
    metric:         string;
}
